# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [2]:
import pandas as pd

In [7]:
df = pd.read_excel("marketing_campaign_dataset.xlsx")

In [9]:
df.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel,Conversion_Rate,Acquisition_Cost,ROI,Location,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,16174,6.29,Chicago,...,NaN,NaN,NaN,NaN,s,NaN,NaN,NaN,NaN,NaN
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,11566,5.61,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,",",NaN,NaN
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,10200,7.18,Los Angeles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,",",NaN
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,12724,5.55,Miami,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,",",NaN,NaN
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,16452,6.50,Los Angeles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,",",NaN,NaN

In [16]:
df.dtypes

Campaign_ID                  int64
Company                        str
Campaign_Type                  str
Target_Audience                str
Duration                       str
Channel                        str
Conversion_Rate            float64
Acquisition_Cost             int64
ROI                        float64
Location                       str
Language                       str
Clicks                       int64
Impressions                  int64
Engagement_Score             int64
Customer_Segment               str
Date                datetime64[us]
CTR                        float64
CPC                        float64
SQL_format                     str
Unnamed: 19                float64
Unnamed: 20                float64
Unnamed: 21                float64
Unnamed: 22                float64
Unnamed: 23                float64
Unnamed: 24                float64
Unnamed: 25                float64
Unnamed: 26                float64
Unnamed: 27                float64
Unnamed: 28                float64
Unnamed: 29                float64
Unnamed: 30                float64
Unnamed: 31                    str
Unnamed: 32                float64
Unnamed: 33                    str
Unnamed: 34                    str
Unnamed: 35                    str
Unnamed: 36                    str
dtype: object

In [18]:
df['ROI'].mean()

np.float64(5.002437850000001)

In [21]:
df.groupby('Channel')['ROI'].mean()

Channel
Email         4.996487
Facebook      5.018699
Google Ads    5.003141
Instagram     4.988706
Website       5.014167
YouTube       4.993754
Name: ROI, dtype: float64

In [23]:
df.sort_values(by='ROI', ascending=False).head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel,Conversion_Rate,Acquisition_Cost,ROI,Location,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
65640,65641,Alpha Innovations,Search,Women 25-34,15 days,Website,0.09,18624,8.0,Miami,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143790,143791,Alpha Innovations,Influencer,Men 18-24,60 days,Website,0.06,17371,8.0,Los Angeles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143503,143504,Innovate Industries,Influencer,Women 35-44,30 days,YouTube,0.04,5889,8.0,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121639,121640,TechCorp,Influencer,Men 18-24,15 days,Google Ads,0.14,7081,8.0,Chicago,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120917,120918,TechCorp,Social Media,Men 18-24,45 days,Website,0.11,6677,8.0,Miami,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df['ctr'] = (df['Clicks'] / df['Impressions']) * 100

In [26]:
df['ctr'].mean()

np.float64(14.0405495333939)

In [27]:
df.groupby('Channel')['ctr'].mean()

Channel
Email         14.054269
Facebook      14.049926
Google Ads    13.918967
Instagram     14.003691
Website       14.097136
YouTube       14.119605
Name: ctr, dtype: float64

In [28]:
df['cpc'] = df['Acquisition_Cost'] / df['Clicks']

In [29]:
df['cpc'].mean()

np.float64(32.00849015169122)

In [30]:
df.groupby('Channel')['cpc'].mean()

Channel
Email         31.881471
Facebook      32.129253
Google Ads    32.309304
Instagram     32.080786
Website       31.779545
YouTube       31.872808
Name: cpc, dtype: float64

In [31]:
df.groupby('Target_Audience')['ROI'].mean()

Target_Audience
All Ages       5.005174
Men 18-24      4.982853
Men 25-34      5.020627
Women 25-34    4.997351
Women 35-44    5.006330
Name: ROI, dtype: float64

In [32]:
df.groupby('Location')['ROI'].mean()

Location
Chicago        5.001590
Houston        5.007203
Los Angeles    5.010876
Miami          5.012282
New York       4.980228
Name: ROI, dtype: float64

In [35]:
df.sort_values(by=['ROI','ctr'], ascending=False).head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel,Conversion_Rate,Acquisition_Cost,ROI,Location,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,ctr,cpc
17685,17686,Alpha Innovations,Search,Men 25-34,45 days,Email,0.02,12127,8.0,Houston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.095395,13.459489
31224,31225,NexGen Systems,Influencer,All Ages,60 days,Website,0.05,6703,8.0,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.853556,8.649032
55641,55642,NexGen Systems,Social Media,All Ages,15 days,Website,0.07,10051,8.0,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.405797,12.470223
186057,186058,NexGen Systems,Influencer,Men 18-24,45 days,Facebook,0.02,11806,8.0,Houston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.668712,15.699468
65236,65237,TechCorp,Search,Women 35-44,15 days,Google Ads,0.06,5257,8.0,Houston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.847361,6.595985

In [36]:
from IPython.display import display
display(df.sort_values(by=['ROI','ctr'], ascending=False).head())

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel,Conversion_Rate,Acquisition_Cost,ROI,Location,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,ctr,cpc
17685,17686,Alpha Innovations,Search,Men 25-34,45 days,Email,0.02,12127,8.0,Houston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.095395,13.459489
31224,31225,NexGen Systems,Influencer,All Ages,60 days,Website,0.05,6703,8.0,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.853556,8.649032
55641,55642,NexGen Systems,Social Media,All Ages,15 days,Website,0.07,10051,8.0,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.405797,12.470223
186057,186058,NexGen Systems,Influencer,Men 18-24,45 days,Facebook,0.02,11806,8.0,Houston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.668712,15.699468
65236,65237,TechCorp,Search,Women 35-44,15 days,Google Ads,0.06,5257,8.0,Houston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.847361,6.595985

In [37]:
print(df.sort_values(by=['ROI','ctr'], ascending=False).head().to_string())

        Campaign_ID            Company Campaign_Type Target_Audience Duration     Channel  Conversion_Rate  Acquisition_Cost  ROI  Location Language  Clicks  Impressions  Engagement_Score     Customer_Segment       Date       CTR        CPC                                                                                                                                                                                SQL_format  Unnamed: 19  Unnamed: 20  Unnamed: 21  Unnamed: 22  Unnamed: 23  Unnamed: 24  Unnamed: 25  Unnamed: 26  Unnamed: 27  Unnamed: 28  Unnamed: 29  Unnamed: 30 Unnamed: 31  Unnamed: 32 Unnamed: 33 Unnamed: 34 Unnamed: 35 Unnamed: 36        ctr        cpc
17685         17686  Alpha Innovations        Search       Men 25-34  45 days       Email             0.02             12127  8.0   Houston   French     901         1216                 3         Fashionistas 2021-06-15  0.116342  11.046434              (17686,'Alpha Innovations','Search','Men 25-34','45 days','Email',0.02,12127,8,'Houston','French',901,1216,3,'Fashionistas','2021-06-15',0.116341886938067,11.0464344941957)          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN         NaN          NaN         NaN         NaN         NaN         NaN  74.095395  13.459489
31224         31225     NexGen Systems    Influencer        All Ages  60 days     Website             0.05              6703  8.0  New York  English     775         1195                 1              Foodies 2021-07-19  0.126058  26.878322                (31225,'NexGen Systems','Influencer','All Ages','60 days','Website',0.05,6703,8,'New York','English',775,1195,1,'Foodies','2021-07-19',0.126057827926657,26.8783216783217)          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN         NaN          NaN         NaN         NaN         NaN         NaN  64.853556   8.649032
55641         55642     NexGen Systems  Social Media        All Ages  15 days     Website             0.07             10051  8.0  New York   German     806         1380                 1  Outdoor Adventurers 2021-06-11  0.113707  30.788650  (55642,'NexGen Systems','Social Media','All Ages','15 days','Website',0.07,10051,8,'New York','German',806,1380,1,'Outdoor Adventurers','2021-06-11',0.113707165109034,30.7886497064579)          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN         NaN          NaN         NaN         NaN         NaN         NaN  58.405797  12.470223
186057       186058     NexGen Systems    Influencer       Men 18-24  45 days    Facebook             0.02             11806  8.0   Houston   German     752         1304                 8         Fashionistas 2021-09-30  0.334686  14.398485         (186058,'NexGen Systems','Influencer','Men 18-24','45 days','Facebook',0.02,11806,8,'Houston','German',752,1304,8,'Fashionistas','2021-09-30',0.334685598377282,14.3984848484848)          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN         NaN          NaN         NaN         NaN         NaN         NaN  57.668712  15.699468
65236         65237           TechCorp        Search     Women 35-44  15 days  Google Ads             0.06              5257  8.0   Houston  Spanish     797         1402                 7     Tech Enthusiasts 2021-09-24  0.096695  19.534642           (65237,'TechCorp','Search','Women 35-44','15 days','Google Ads',0.06,5257,8,'Houston','Spanish',797,1402,7,'Tech Enthusiasts','2021-09-24',0.0966949531040643,19.5346420323326)          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN          NaN         NaN          NaN         NaN         NaN         NaN         NaN  56.847361   6.595985

In [38]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [39]:
df.drop(columns=['SQL_format'], inplace=True)

print(df.head().to_string())

In [41]:
print(df.head().to_string())

   Campaign_ID              Company Campaign_Type Target_Audience Duration     Channel  Conversion_Rate  Acquisition_Cost   ROI     Location  Language  Clicks  Impressions  Engagement_Score     Customer_Segment       Date       CTR        CPC        ctr        cpc
0            1  Innovate Industries         Email       Men 18-24  30 days  Google Ads             0.04             16174  6.29      Chicago   Spanish     506         1922                 6    Health & Wellness 2021-01-01       NaN        NaN  26.326743  31.964427
1            2       NexGen Systems         Email     Women 35-44  60 days  Google Ads             0.12             11566  5.61     New York    German     116         7523                 7         Fashionistas 2021-01-02  0.263267  31.964427   1.541938  99.706897
2            3    Alpha Innovations    Influencer       Men 25-34  30 days     YouTube             0.07             10200  7.18  Los Angeles    French     584         7698                 1  Outdoor Adventurers 2021-01-03  0.015419  99.706897   7.586386  17.465753
3            4   DataTech Solutions       Display        All Ages  60 days     YouTube             0.11             12724  5.55        Miami  Mandarin     217         1820                 7    Health & Wellness 2021-01-04  0.075864  17.465753  11.923077  58.635945
4            5       NexGen Systems         Email       Men 25-34  15 days     YouTube             0.05             16452  6.50  Los Angeles  Mandarin     379         4201                 3    Health & Wellness 2021-01-05  0.119231  58.635945   9.021662  43.408971

In [42]:
df.drop(columns=['CTR','CPC'], inplace=True)

In [43]:
print(df.head().to_string())

   Campaign_ID              Company Campaign_Type Target_Audience Duration     Channel  Conversion_Rate  Acquisition_Cost   ROI     Location  Language  Clicks  Impressions  Engagement_Score     Customer_Segment       Date        ctr        cpc
0            1  Innovate Industries         Email       Men 18-24  30 days  Google Ads             0.04             16174  6.29      Chicago   Spanish     506         1922                 6    Health & Wellness 2021-01-01  26.326743  31.964427
1            2       NexGen Systems         Email     Women 35-44  60 days  Google Ads             0.12             11566  5.61     New York    German     116         7523                 7         Fashionistas 2021-01-02   1.541938  99.706897
2            3    Alpha Innovations    Influencer       Men 25-34  30 days     YouTube             0.07             10200  7.18  Los Angeles    French     584         7698                 1  Outdoor Adventurers 2021-01-03   7.586386  17.465753
3            4   DataTech Solutions       Display        All Ages  60 days     YouTube             0.11             12724  5.55        Miami  Mandarin     217         1820                 7    Health & Wellness 2021-01-04  11.923077  58.635945
4            5       NexGen Systems         Email       Men 25-34  15 days     YouTube             0.05             16452  6.50  Los Angeles  Mandarin     379         4201                 3    Health & Wellness 2021-01-05   9.021662  43.408971

In [47]:
result = df.groupby('Channel')[['ROI','ctr','cpc']].mean().sort_values(by='ROI', ascending=False)

print(result.to_string())

                 ROI        ctr        cpc
Channel
Facebook    5.018699  14.049926  32.129253
Website     5.014167  14.097136  31.779545
Google Ads  5.003141  13.918967  32.309304
Email       4.996487  14.054269  31.881471
YouTube     4.993754  14.119605  31.872808
Instagram   4.988706  14.003691  32.080786

In [48]:
audience = df.groupby('Target_Audience')['ROI'].mean().sort_values(ascending=False)

print(audience.to_string())

Target_Audience
Men 25-34      5.020627
Women 35-44    5.006330
All Ages       5.005174
Women 25-34    4.997351
Men 18-24      4.982853

In [49]:
location = df.groupby('Location')['ROI'].mean().sort_values(ascending=False)

print(location.to_string())

Location
Miami          5.012282
Los Angeles    5.010876
Houston        5.007203
Chicago        5.001590
New York       4.980228

In [50]:
top_campaigns = df.sort_values(by=['ROI','ctr'], ascending=False).head()

print(top_campaigns.to_string())

        Campaign_ID            Company Campaign_Type Target_Audience Duration     Channel  Conversion_Rate  Acquisition_Cost  ROI  Location Language  Clicks  Impressions  Engagement_Score     Customer_Segment       Date        ctr        cpc
17685         17686  Alpha Innovations        Search       Men 25-34  45 days       Email             0.02             12127  8.0   Houston   French     901         1216                 3         Fashionistas 2021-06-15  74.095395  13.459489
31224         31225     NexGen Systems    Influencer        All Ages  60 days     Website             0.05              6703  8.0  New York  English     775         1195                 1              Foodies 2021-07-19  64.853556   8.649032
55641         55642     NexGen Systems  Social Media        All Ages  15 days     Website             0.07             10051  8.0  New York   German     806         1380                 1  Outdoor Adventurers 2021-06-11  58.405797  12.470223
186057       186058     NexGen Systems    Influencer       Men 18-24  45 days    Facebook             0.02             11806  8.0   Houston   German     752         1304                 8         Fashionistas 2021-09-30  57.668712  15.699468
65236         65237           TechCorp        Search     Women 35-44  15 days  Google Ads             0.06              5257  8.0   Houston  Spanish     797         1402                 7     Tech Enthusiasts 2021-09-24  56.847361   6.595985

In [51]:
cpc_analysis = df.groupby('Channel')['cpc'].mean().sort_values()

print(cpc_analysis.to_string())

Channel
Website       31.779545
YouTube       31.872808
Email         31.881471
Instagram     32.080786
Facebook      32.129253
Google Ads    32.309304